#baseURL = "/"
baseURL = "https://fabioprataviera.netlify.app/"
languageCode = "en-us"
title = "Fábio Prataviera"
description = "An easy reading Hugo blog with night-mode."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "An easy reading Hugo blog with night-mode."
    logo = "favicon/IMG_20200825_131313.png"
    twitterAuthor = "@Prataviera2020"
    githubUsername = "fabiopviera"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox?compose=new"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/fabiopviera"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "http://lattes.cnpq.br/3225385085167748"
    name = "fab far fa-address-book"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/f%C3%A1bio-prataviera-495720116/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://scholar.google.com.br/citations?user=bQ9UhREAAAAJ&hl=pt-BR"
    name = "fab fa-google"
    weight = 5
